apiVersion: v2
name: wordpress-mcp
description: A Helm chart for WordPress with MCP Integration Plugin
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: mariadb
    version: 11.4.2
    repository: https://charts.bitnami.com/bitnami