apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress-tenant.fullname" . }}
  labels:
    {{- include "wordpress-tenant.labels" . | nindent 4 }}
data:
  # WordPress configuration
  wordpress-config.php: |
    <?php
    // Tenant-specific WordPress configuration
    define('DB_HOST', '{{ if .Values.database.external.enabled }}{{ .Values.database.external.host }}:{{ .Values.database.external.port }}{{ else }}{{ include "wordpress-tenant.fullname" . }}-mariadb:3306{{ end }}');
    define('DB_NAME', '{{ if .Values.database.external.enabled }}{{ .Values.database.external.name }}{{ else }}{{ .Values.database.internal.auth.database }}{{ end }}');
    define('DB_USER', '{{ if .Values.database.external.enabled }}{{ .Values.database.external.user }}{{ else }}{{ .Values.database.internal.auth.username }}{{ end }}');
    
    // WordPress debugging
    define('WP_DEBUG', {{ .Values.wordpress.config.debug }});
    define('WP_DEBUG_LOG', {{ .Values.wordpress.config.debug }});
    define('WP_DEBUG_DISPLAY', false);
    
    // WordPress environment
    define('WP_ENVIRONMENT_TYPE', '{{ .Values.wordpress.config.environment }}');
    
    // Table prefix
    $table_prefix = '{{ .Values.wordpress.config.tablePrefix }}';
    
    // WordPress URLs
    define('WP_HOME', '{{ .Values.wordpress.site.url }}');
    define('WP_SITEURL', '{{ .Values.wordpress.site.url }}');
    
    // Additional configuration
    define('WP_POST_REVISIONS', 3);
    define('AUTOMATIC_UPDATER_DISABLED', true);
    define('DISALLOW_FILE_EDIT', true);
    
    {{- if .Values.wordpress.mcp.enabled }}
    // MCP Plugin configuration
    define('WP_MCP_ENABLED', true);
    {{- end }}
    
    {{- if .Values.wordpress.auth.oauth.enabled }}
    // OAuth configuration
    define('OIDC_CLIENT_ID', '{{ .Values.wordpress.auth.oauth.clientId }}');
    define('OIDC_ENDPOINT_LOGIN_URL', 'http://authentik-server.{{ .Values.global.sharedServicesNamespace }}.svc.cluster.local:9000/application/o/authorize/');
    define('OIDC_ENDPOINT_USERINFO_URL', 'http://authentik-server.{{ .Values.global.sharedServicesNamespace }}.svc.cluster.local:9000/application/o/userinfo/');
    define('OIDC_ENDPOINT_TOKEN_URL', 'http://authentik-server.{{ .Values.global.sharedServicesNamespace }}.svc.cluster.local:9000/application/o/token/');
    {{- end }}
  
  # wp-cli configuration
  wp-cli.yml: |
    path: /var/www/html
    core config:
      extra-php: |
        define('WP_ENVIRONMENT_TYPE', '{{ .Values.wordpress.config.environment }}');
        {{- if .Values.wordpress.config.debug }}
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        {{- end }}