apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-tenant.fullname" . }}
  labels:
    {{- include "wordpress-tenant.labels" . | nindent 4 }}
type: Opaque
data:
  # WordPress admin password
  admin-password: {{ .Values.wordpress.site.adminPassword | default (randAlphaNum 16) | b64enc }}
  
  # MCP API key
  {{- if .Values.wordpress.mcp.enabled }}
  mcp-api-key: {{ .Values.wordpress.mcp.apiKey | default (randAlphaNum 32) | b64enc }}
  {{- end }}
  
  # OAuth client secret
  {{- if .Values.wordpress.auth.oauth.enabled }}
  oauth-client-secret: {{ .Values.wordpress.auth.oauth.clientSecret | default (randAlphaNum 32) | b64enc }}
  {{- end }}
  
  # WordPress security keys
  {{- $keys := list "auth_key" "secure_auth_key" "logged_in_key" "nonce_key" "auth_salt" "secure_auth_salt" "logged_in_salt" "nonce_salt" }}
  {{- range $key := $keys }}
  {{- $value := index $.Values.wordpress.auth.keys $key | default (randAlphaNum 64) }}
  {{ $key | replace "_" "-" }}: {{ $value | b64enc }}
  {{- end }}

---
{{- if .Values.database.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-tenant.fullname" . }}-db
  labels:
    {{- include "wordpress-tenant.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.database.external.password | b64enc }}
{{- end }}