version: '3.8'

services:
  # MariaDB Database for WordPress
  mysql:
    image: mariadb:10.6
    container_name: wp-mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress_password
      MARIADB_ROOT_PASSWORD: root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp-network
    ports:
      - "3306:3306"

  # WordPress with MCP Plugin
  wordpress:
    image: wordpress:latest
    container_name: wp-instance
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress/plugins:/var/www/html/wp-content/plugins
    networks:
      - wp-network
    ports:
      - "8080:80"

  # OpenWebUI
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui-instance
    restart: unless-stopped
    environment:
      - WEBUI_NAME=WordPress Integration Demo
      - WEBUI_URL=http://localhost:3000
      - DEFAULT_USER_ROLE=admin
      - ENABLE_SIGNUP=true
    volumes:
      - openwebui_data:/app/backend/data
      - ./openwebui/config:/app/backend/config
    networks:
      - wp-network
    ports:
      - "3000:8080"



volumes:
  mariadb_data:
  wordpress_data:
  openwebui_data:

networks:
  wp-network:
    driver: bridge