# Default values for openwebui chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# OpenWebUI configuration
openwebui:
  # Container image configuration
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: main
    pullPolicy: IfNotPresent
  
  # Resource requirements
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  # Replica count (typically 1 for shared instance)
  replicaCount: 1
  
  # OpenWebUI configuration
  config:
    # Web UI name
    name: "WordPress Integration Portal"
    # Base URL
    url: "http://openwebui.local"
    # Default user role for new users
    defaultUserRole: "user"
    # Enable/disable user signup
    enableSignup: false
    # Admin settings
    adminSettings:
      # Default admin user (created on first run)
      adminUser: "admin"
      adminEmail: "admin@example.com"
      # Password will be generated if not provided
      adminPassword: ""
  
  # OAuth/SSO Configuration (Authentik integration)
  oauth:
    enabled: true
    # OAuth provider configuration
    clientId: "openwebui"
    clientSecret: ""  # Will be generated if empty
    scopes: "openid profile email"
    providerName: "Authentik"
    # OAuth URLs (will be constructed automatically)
    authorizationUrl: ""
    tokenUrl: ""
    userinfoUrl: ""
    redirectUri: ""
  
  # Data persistence
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 10Gi
    mountPath: /app/backend/data
  
  # Additional environment variables
  extraEnvVars: []
    # - name: CUSTOM_VAR
    #   value: "custom_value"

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: openwebui.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: openwebui-tls
  #    hosts:
  #      - openwebui.local

# Load Balancer configuration (IONOS specific)
loadBalancer:
  enabled: false
  # IONOS LoadBalancer annotations
  annotations:
    service.beta.kubernetes.io/ionos-loadbalancer-forwarding-rules: ""
  # Static IP configuration
  loadBalancerIP: ""

# Security Context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

podSecurityContext:
  fsGroup: 1000

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selector and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

# Service Account
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# RBAC configuration
rbac:
  # Create RBAC resources
  create: true

# Network Policies
networkPolicy:
  # Enable network policies
  enabled: true
  # Allow ingress from tenant namespaces
  allowFromTenantNamespaces: true
  # Tenant namespace pattern (for allowing connections)
  tenantNamespacePattern: "tenant-*"
  # Additional ingress rules
  ingress: []
  # Additional egress rules  
  egress: []

# Monitoring and observability
monitoring:
  # Enable ServiceMonitor for Prometheus
  serviceMonitor:
    enabled: false
    interval: 30s
    path: /api/v1/health
  
  # Pod annotations for monitoring
  podAnnotations: {}

# Backup configuration
backup:
  enabled: false
  # Backup schedule (cron format)
  schedule: "0 2 * * *"
  # Retention policy
  retention: "7d"
  # Storage for backups
  storage:
    size: 20Gi
    storageClass: ""

# Configuration for shared services namespace
sharedServicesNamespace: "shared-services"