# Default values for openwebui
replicaCount: 1

image:
  repository: ghcr.io/open-webui/open-webui
  pullPolicy: IfNotPresent
  tag: "main"

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# OpenWebUI specific configuration
openwebui:
  name: "WordPress Integration Demo"
  url: "http://localhost:3000"
  defaultUserRole: "admin"
  enableSignup: true
  
  # Integration settings
  integration:
    wordpress:
      apiUrl: "http://wordpress-mcp:80/wp-json/mcp/v1"
      apiKey: "demo-api-key-poc"

persistence:
  enabled: true
  size: 8Gi